### PR TITLE
Fix CI by adding .travis.yml

### PR DESCRIPTION
**Pull request by dhmlau**
Fix CI by adding .travis.yml

### CODE REVIEW

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please
`http://www.webservicex.net/periodictable.asmx?WSDL` used in the test is now available. kicking off the test.

**Comment by b-admike** [comment]
@dhmlau just need to rebase, and we should be able to land this patch.

**Comment by dhmlau** [comment]
Rebased. See if CI is green :)

**Pull request merged**
