### PR TITLE
Use juggler@3 and loopback@3 for testing

### PR DESCRIPTION
**Pull request by Amir-61**

### CODE REVIEW

**Comment by gunjpan** [comment]
@slnode test please

**Comment by 0candy** [comment]
@Amir-61 Do we still need this PR? If so, it probably needs to be updated.

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
Not sure if it is needed or not... You are the owner of this repo, you may know better. I close this PR.

**Pull request closed without merging**
